jobs:
  generate-keystore-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create keystore.properties
         run: |
          echo "storeFile=pxgmapsandroid-key" > keystore.properties
          echo "storePassword=${{ secrets.APP_SIGN_STORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.APP_SIGN_KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.APP_SIGN_KEY_PASSWORD }}" >> keystore.properties

